version: 2

builds:
  - skip: true

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
  extra_files:
    - ./geol-build/*

homebrew_casks:
  - # Name of the recipe
    name: geol

    # Your app's description.
    description: "geol, the cli to efficiently display product end-of-life dates in your terminal using the endoflife.date API."

    # Homepage is the link to the project page of the formula.
    homepage: https://github.com/opt-nc/geol

    # Repository to push the generated files to.
    repository:
      owner: opt-nc
      name: homebrew-tap
      token: "{{ .Env.PUBLIC_HOMEBREW_TAP_TOKEN }}"

    manpages:
      - "manpages/geol.1.gz"

    # Completions for different shells
    #
    # Templates: allowed.  
    completions:
      bash: "completions/geol.bash"
      zsh: "completions/geol.zsh"
      fish: "completions/geol.fish"

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@opt.nc

    # The project name and current git tag are used in the format string.
    #
    # Templates: allowed
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    
    # Directory inside the repository to put the formula.
    directory: Casks

    # The formula license.
    license: Apache-2.0

    skip_upload: auto

    # This information will be used to build the URL section of your Cask.
    #
    # You can set the template, as well as additional parameters.
    # These parameters can be used to provide extra headers, cookies, or other
    # download requirements for your application.
    # See https://docs.brew.sh/Cask-Cookbook#additional-url-parameters for more details.
    #
    # All fields are optional.
    url:
      template: "https://github.com/opt-nc/geol/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      # Download strategy or format specification
      # See official Cask Cookbook for allowed values.
      # Templates: allowed.
      using: ":homebrew_curl"
