version: "3"

tasks:
  build:
    desc: Build the app
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/geol main.go

  run:
    desc: Run the app
    cmds:
      - GOFLAGS=-mod=mod go run main.go
  clean:
    desc: Remove all the build files
    cmds:
      - rm -rf bin/
      - rm -rf dist/
