name: Test Geol Installation

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 15 * * 0'


permissions:
  contents: read

jobs:
  install-geol:          
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      
      - name: Install Geol
        uses: opt-nc/geol-action@8b85537a2997854f79cd5d66820b972035120992
        #with:
          #version: 'v2.12.1' # Optional: Specify a specific version of Geol to install. If not provided, the latest version will be installed.
      
      - name: Verify Geol Installation
        run: |
          geol about

      - name: Run Geol Check stack status # will fail if the .geol file is not present, you can use the geol check init command to create one
        run: |
          geol check --strict